name: Scheduled workflow
on:
  push:
  schedule:
    - cron: '*/7 * * * *'
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Set time
        run: echo "::set-output name=TIME::$(date)"
        id: set-time
      - name: Starting the nightly build at ${{ steps.set-time.outputs.TIME }}
        run: echo "The current time is ${{ steps.set-time.outputs.TIME }}"    
