name: Nightly Build
on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Set time
        run: echo "::set-output name=TIME::$(date +%F)"
        id: set-time
      - name: Starting the nightly build at ${{ steps.set-time.outputs.TIME }}
        run: echo "The current time is ${{ steps.set-time.outputs.TIME }}"
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Create the tarball
        run: tar -cvf nightly-${{ steps.set-time.outputs.TIME }}.tar ./*
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
         name: nightly-${{ steps.set-time.outputs.TIME }}.tar
         path: ./nightly-$(date +%F).tar

